deployment:
  tasks:
    - export DEPLOYPATH=/home/softmine/public_html/usa
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R components $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R thank-you $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    
