deployment:
  tasks:
    - export DEPLOYPATH=/home/softmine/public_html/usa
    - /bin/cp /assets $DEPLOYPATH
    - /bin/cp /components $DEPLOYPATH
    - /bin/cp /css $DEPLOYPATH
    - /bin/cp index-php $DEPLOYPATH
